### ISSUE TITLE
Some icons don't show correctly

### ISSUE THREAD

**Issue by loloontheair** [TheWebShop/bootstrap-shortcodes#37]
Hello,

Some icons don't show correctly on Safari Mac latest version -bell, bookmark, briefcase, camera, wrench, etc... 

So I did some research and I was able to fix the issue with the following help:

http://stackoverflow.com/questions/19417040/some-of-bootstrap3-glyphicons-are-not-displayed-correctly-on-phonegap-android-we

I would recommend to change the file some next version in Wordpress is not lost.

Thanks,
Laurent

**Comment by alexisju** [comment]
I observe the same issue on several wordpress websites...

**Comment by No3x** [comment]
I was able to reproduce this. I also fixed this by updating the bootstrap fonts to 3.3.5 too.
@Sinetheta you forgot to update them in 3d8d5d362e1bce805ffb9d440214a8e83d47cb4c.

**Comment by Sinetheta** [comment]
Thanks @No3x I'll push a new version tonight.
