### ISSUE TITLE
Doesn't work with 4.01?

### ISSUE THREAD

**Issue by d3vit** [TheWebShop/bootstrap-shortcodes#45]
Hello,

Not working with the visual editor in 4.01. Any plans to release an update?

Thanks!

**Comment by No3x** [comment]
Hi @d3vit,
I can not confirm this for 4.1. Just tested it on my website. Do you really mean 4.0.1 with ```4.01```?
Please make sure to enable the toolbar and give additional information about the problem.
![itworks](https://cloud.githubusercontent.com/assets/2690708/5632881/9fb35130-95d2-11e4-95da-a3e91653351a.PNG)

**Comment by d3vit** [comment]
Hah. Yeaup -- realized that and immediately closed the issue. Noob moment. Thanks for the quick response!

**Comment by No3x** [comment]
Oops thought you hit the Close button by mistake so soon.
Enjoy the plugin :+1: 

We should add this to the FAQ.
