### ISSUE TITLE
How to make a row inside a row?

### ISSUE THREAD

**Issue by eduardoarandah** [TheWebShop/bootstrap-shortcodes#48]
how to divide a row inside a row? 

this code doesn't work:
[bs_row class="row"]
[bs_col class="col-xs-6"]

[bs_row class="row"]
[bs_col class="col-xs-6"]subdivision 1[/bs_col]
[bs_col class="col-xs-6"]subdivision 2[/bs_col]
[/bs_row]

[/bs_col]
[bs_col class="col-xs-6"]division 2[/bs_col]
[/bs_row]

**Comment by Sinetheta** [comment]
Unfortunately this isn't really feasible in Wordpress http://codex.wordpress.org/Shortcode_API#Nested_Shortcodes

> This is a limitation of the context-free regexp parser used by do_shortcode() - it is very fast but does not count levels of nesting, so it can't match each opening tag with its correct closing tag in these cases.
