### ISSUE TITLE
Nav toggle not closing

### ISSUE THREAD

**Issue by DianeLawson** [TheWebShop/bootstrap-shortcodes#50]
Hello friends,

I installed your very good plugin couple of days ago. However, today I find out a bug or may be I am missing something. When I click on toggle menu, it drops down. However, when I click to close it, it just refreshes and don't slide up. When I deactivate your plugin, it starts working.

Your swift response will be highly appreciated as I am very interested to use your plugin..........

Thank you!

**Comment by No3x** [comment]
Hello @DianeLawson,

do you use a WordPress theme based on bootstrap? Or do you mean a specific component from the plugin. I'm not sure since we don't provide a nav component.

**Comment by DianeLawson** [comment]
Yes, I am making a theme using bootstrap as framework.

**Comment by No3x** [comment]
Ah, all right. I use also a bootstrap theme and have bootstrap shotcodes installed - there are no conflicts. So I think you should check your theme first. The theme I'm using is called [Arcade Basic](https://themes.trac.wordpress.org/browser/arcade-basic/) and also the code is there if you want to take a look how they manage navs.
I'm not the maintainer but I think you should check your code again.

**Comment by DianeLawson** [comment]
Got that.... same as Bootstrap CSS, you have js file too, and duplication of this file is making things complicated. Thanks dear for your kind help. It seems, I don't need to enqueue the bootstraps files anymore until I am using this plugin.... Thank you once again

**Comment by No3x** [comment]
Wait wait wait..
You should ship it with your theme instead relying on the plugin ones if you build a theme that uses bootstrap things.

**Comment by DianeLawson** [comment]
Yes, it would remain in my function.php. I am just commenting it out so If I ever remove this plugin, I will activate those lines. Currently, working on local server so don't have any idea about on outcomes but I am sure that would be good on live server too.

**Comment by No3x** [comment]
All right. Happy developing!

**Comment by DianeLawson** [comment]
Thanks Dear... Quite scary though :) :+1:

**Comment by No3x** [comment]
You are welcome.

**Comment by Sinetheta** [comment]
Awesome, thanks for jumping on this @No3x
