### ISSUE TITLE
Not compatible with Bootstrap-based plugins like Roots/Sage

### ISSUE THREAD

**Issue by zephod** [TheWebShop/bootstrap-shortcodes#51]
This plugin installs its own copy of Bootstrap's CSS and JS, which most users (eg. my team!) absolutely don't want. We've got our own assets pipeline and we're not using the stock CSS file, we're compiling down about fifty LESS files and hosting on a CDN.

The plugin looks like a good idea because it presents as a shortcode plugin, which we want, but this issue forces us to use something else. I suggest making "Include Bootstrap CSS & JS" a toggle option?

Also if you're going to include those scripts at all they need to go in the footer otherwise they'll appear before jQuery.

**Comment by zephod** [comment]
Ha ha, I've just seen those options _do_ exist but we hadn't found the Admin menu.

Maybe you could link to the admin menu from the plugin activation page? The common pattern is to have `Settings | Deactivate` links.

**Comment by Sinetheta** [comment]
Glad you found the settings @zephod, thanks for the tip to add them to the activation page.
