### ISSUE TITLE
btn-block missing

### ISSUE THREAD

**Issue by CDESmith** [TheWebShop/bootstrap-shortcodes#52]
There doesn't appear to be any support for applying the above class to buttons.

**Comment by No3x** [comment]
Right. Are you already working on this?

**Comment by Sinetheta** [comment]
If this is still around tonight I'll do some house cleaning. Close issues, push a release, etc.

**Comment by No3x** [comment]
@Sinetheta "push a release" what are you going to push? Because there are no commits since the last release I assume you want to fix this issue. Did I got this right?

Gosh, there are also a lot of issues on the WordPress support forums. Is nobody caring about them?

**Comment by Sinetheta** [comment]
Yes @No3x I meant that I would merge anything that folks come up with today, and address anything that's still outstanding in 8 hours.

Unfortunately no, I've never looked at the Wordpress, just always tried to direct traffic here through the readme.
