### ISSUE TITLE
Images on wordpress.org

### ISSUE THREAD

**Issue by No3x** [TheWebShop/bootstrap-shortcodes#55]
are out of sync with this repository. This results also in wrong captions. 

Could we setup gitter chat for such minor issues?

**Comment by Sinetheta** [comment]
Cute, I'd never heard of that. https://gitter.im/TheWebShop/bootstrap-shortcodes

**Comment by Sinetheta** [comment]
Fixed the images. Sorry I didn't notice that they had all changed from jpg to png and I'm not very good with SVN, because it's awful...
