### ISSUE TITLE
Does this work with non-bootstrap themes too?

### ISSUE THREAD

**Issue by ovizii** [TheWebShop/bootstrap-shortcodes#60]
I'm just asking as I have found another plugin which works but its limiting the shortcodes you can use unless you buy their PRO version.

If this plugin needs bootstrap already enable inside a theme, do you have any directions on how to manually add that to an existing theme?

**Comment by No3x** [comment]
Hi @ovizii,
have you noticed the Settings > BS Shortcodes?

**Comment by ovizii** [comment]
Nope, I haven't installed it yet, I was looking at at least 5 different plugins and some mentioned this feature some didn't. From your answer I assume it does so I'll go ahead and give it a try :-)

**Comment by No3x** [comment]
This are the settings:
![bs-options](https://cloud.githubusercontent.com/assets/2690708/9628065/c2f87f42-5168-11e5-874e-4ad52afa8cbd.PNG)

**Comment by ovizii** [comment]
Awesome, thanks, maybe add that to the screen shtos tab in WO.ORG too.

**Comment by No3x** [comment]
You are welcome! Yes we should add this.
