### ISSUE TITLE
Incompatible with Bootstrap Select?

### ISSUE THREAD

**Issue by moultz** [TheWebShop/bootstrap-shortcodes#66]
Hi I've been trying to use both Bootstrap Select (https://silviomoreto.github.io/bootstrap-select/) and your plugin and I've found that it breaks the <select> element. When clicking on the <select> element the <option>s/dropdown does not appear.

I'm using WordPress 4.5, I fixed this by commenting out line number 54 in bootstrap-shortcodes.php
`wp_enqueue_script( 'bs_bootstrap', plugins_url( 'js/bootstrap.js', __FILE__ ) , array( 'jquery' ) );`

I think you're using an outdated bootstrap.js file.

Best,
Henry

**Comment by Sinetheta** [comment]
Thanks @moultz, since many other plugins and themes also add the Bootstrap CSS and JS that line is actually optional. If you go into your settings you'll see a checkbox for "Twitter Bootstrap JS".

**Comment by moultz** [comment]
Thank you!
