### ISSUE TITLE
dropdown tabs does not works on iOS 10

### ISSUE THREAD

**Issue by va-ac** [TheWebShop/bootstrap-shortcodes#75]
Hi I am using a dropdown tab list that works fine on android phones but when i try to use it on iOS 10 is not working the touch event.
you can see an example here: http://cordillera.miciudadinteligente.com/dev/test-menu/
Thanks for your help!!!

**Comment by Sinetheta** [comment]
Sorry not to have gotten back to you sooner @va-ac but you're missing an `href` in your dropdown toggle. This is a known issue with bootstrap 3 that will only create a problem in ios http://stackoverflow.com/a/20963048
