### ISSUE TITLE
Are there any security issues on latest WordPress installs?

### ISSUE THREAD

**Issue by mrglutton** [TheWebShop/bootstrap-shortcodes#78]
I inherited old WP isntallation that had problems with viruses. I recreated the site anew on another hosting, and installed this plugin manually. However, I am not sure of the safety of the plugin as it is very old.

Any info is appreciated!

**Comment by No3x** [comment]
Hi @mrglutton,
there are no security issues knwon to me.

**Comment by mrglutton** [comment]
Thank you very much for reply, I appreciate it.
